[workspace]
members = [
    "crates/storage",
    "crates/core",
    "crates/rpc",
    "crates/consensus",
    "crates/net", 
    "cmd/reec", 
    "cmd/ef_tests",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
reec-consensus = { path = "./crates/consesnsus"}
reec-core = { path = "./crates/core" }
reec-net = { path = "./crates/net" }
reec-rpc = { path = "./crates/rpc" }
reec-storage = { path = "./crates/storage" }

ethereum-types = "0.14.1"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = "0.3.0"
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.117"
libmdbx = { version = "0.4.0", features = ["orm"] }
bytes = "1.6.0"
tokio = { version = "1.38.0", features = ["full"] }
thiserror = "1.0.61"
hex = "0.4.3"
lazy_static = "1.5.0"
sha3 = "0.10.8"

