[package]
name = "reec"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5.27", features = ["cargo"] }
ethereum-types.workspace = true
rpc.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
