[package]
name = "reec-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
reec-core.workspace = true
ethereum-types = "0.14.1"
libmdbx = { workspace = true, optional = true }
anyhow = "1.0.86"
bytes.workspace = true
tracing.workspace = true
thiserror.workspace = true
# patricia-merkle-tree.workspace = true
sha3.workspace = true
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"

[features]
default = ["in_memory", "libmdbx"]
in_memory = []
libmdbx = ["dep:libmdbx"]

[dev-dependencies]
hex.workspace = true

[lib]
path = "./storage.rs"