[package]
name = "reec-reec"
version.workspace = true
edition.workspace = true

[dependencies]
reec-blockchain.workspace = true
reec-rpc.workspace = true
reec-core.workspace = true
reec-net.workspace = true
reec-storage.workspace = true
reec-evm.workspace = true


bytes.workspace = true
hex.workspace = true
clap = { version = "4.5.27", features = ["cargo"] }
ethereum-types.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde_json.workspace = true
tokio = { version = "1.38.0", features = ["full"] }
anyhow = "1.0.86"
rand = "0.8.5"
k256 = { version = "0.13.3", features = ["ecdh"] }

[[bin]]
name = "reec"
path = "./reec.rs"
