[package]
name = "reec-core"
version.workspace = true
edition.workspace = true

[dependencies]
bytes.workspace = true
hex.workspace = true
lazy_static.workspace = true
ethereum-types ={ version = "0.14.1", features = ["serialize"]}
tinyvec = "1.8.1"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
keccak-hash = "0.10.0"
sha3.workspace = true
secp256k1 = { version = "0.29", default-features = false, features = [
     "global-context",
     "recovery",
 ] }

[dev-dependencies]
hex-literal = "0.4.1"

[lib]
path = "./core.rs"

